services:
  finance-db:
    image: docker.io/postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: finance_tracker
    volumes:
      - finance_tracker_pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"


volumes:
  finance_tracker_pgdata:
