services:
  minio:
    image: docker.io/minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
      MINIO_DEFAULT_BUCKETS: finance-documents 
    volumes:
      - miniodata:/data
    ports:
      - "9000:9000" # S3 API
      - "9001:9001" # Web Console
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3


  finance-db:
    image: docker.io/postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: finance_tracker
    volumes:
      - finance_tracker_pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  redis:
    image: docker.io/library/redis:7-alpine
    container_name: montte-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5


volumes:
  finance_tracker_pgdata:
  miniodata:
  redis_data:

